import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ja">
            <head>
                <title>【開発中】オートコンプリート</title>
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    );
}

const touchHandler = (event) => {
    if (event.touches.length > 1) {
      event.preventDefault();
    }
  };
  document.addEventListener('touchstart', touchHandler, {
    passive: false
  });